from tkinter.tix import CELL


WIDTH= 1080
HEIGHT= 720
GRID_SIZE= 14
CELL_COUNT = GRID_SIZE **2
MINE_COUNT= CELL_COUNT // 6
LEFT_CELL = CELL_COUNT - MINE_COUNT
LIFE_COUNT =3

# LEFT_LABEL_WIDTH = 5
# LEFT_LABEL_HEIGHT = 2